version: '3'

networks:
  scrapynet:

services:
  scrapyd:
    build:
      context: scrapy
    volumes:
    - ./projects:/projects
    ports:
    - "6801:6801"
    networks:
    - scrapynet
    container_name: scrapy
